/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappTemplatesRouteImport } from './routes/whatsapp-templates'
import { Route as WalletViewRouteImport } from './routes/wallet-view'
import { Route as ThirdPartyRouteImport } from './routes/third-party'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as DiscountCardRouteImport } from './routes/discount-card'
import { Route as CollectedRouteImport } from './routes/collected'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappTemplatesRoute = WhatsappTemplatesRouteImport.update({
  id: '/whatsapp-templates',
  path: '/whatsapp-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletViewRoute = WalletViewRouteImport.update({
  id: '/wallet-view',
  path: '/wallet-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ThirdPartyRoute = ThirdPartyRouteImport.update({
  id: '/third-party',
  path: '/third-party',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountCardRoute = DiscountCardRouteImport.update({
  id: '/discount-card',
  path: '/discount-card',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectedRoute = CollectedRouteImport.update({
  id: '/collected',
  path: '/collected',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/collected': typeof CollectedRoute
  '/discount-card': typeof DiscountCardRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/third-party': typeof ThirdPartyRoute
  '/wallet-view': typeof WalletViewRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/collected': typeof CollectedRoute
  '/discount-card': typeof DiscountCardRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/third-party': typeof ThirdPartyRoute
  '/wallet-view': typeof WalletViewRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/collected': typeof CollectedRoute
  '/discount-card': typeof DiscountCardRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/third-party': typeof ThirdPartyRoute
  '/wallet-view': typeof WalletViewRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/collected'
    | '/discount-card'
    | '/lookup'
    | '/mail'
    | '/third-party'
    | '/wallet-view'
    | '/whatsapp-templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/collected'
    | '/discount-card'
    | '/lookup'
    | '/mail'
    | '/third-party'
    | '/wallet-view'
    | '/whatsapp-templates'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/collected'
    | '/discount-card'
    | '/lookup'
    | '/mail'
    | '/third-party'
    | '/wallet-view'
    | '/whatsapp-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CollectedRoute: typeof CollectedRoute
  DiscountCardRoute: typeof DiscountCardRoute
  LookupRoute: typeof LookupRoute
  MailRoute: typeof MailRoute
  ThirdPartyRoute: typeof ThirdPartyRoute
  WalletViewRoute: typeof WalletViewRoute
  WhatsappTemplatesRoute: typeof WhatsappTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-templates': {
      id: '/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/whatsapp-templates'
      preLoaderRoute: typeof WhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet-view': {
      id: '/wallet-view'
      path: '/wallet-view'
      fullPath: '/wallet-view'
      preLoaderRoute: typeof WalletViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party': {
      id: '/third-party'
      path: '/third-party'
      fullPath: '/third-party'
      preLoaderRoute: typeof ThirdPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-card': {
      id: '/discount-card'
      path: '/discount-card'
      fullPath: '/discount-card'
      preLoaderRoute: typeof DiscountCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collected': {
      id: '/collected'
      path: '/collected'
      fullPath: '/collected'
      preLoaderRoute: typeof CollectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CollectedRoute: CollectedRoute,
  DiscountCardRoute: DiscountCardRoute,
  LookupRoute: LookupRoute,
  MailRoute: MailRoute,
  ThirdPartyRoute: ThirdPartyRoute,
  WalletViewRoute: WalletViewRoute,
  WhatsappTemplatesRoute: WhatsappTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
